// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_6-FJ9M1p6GPjoHm9ZmFA55ezwKlCXY',
    appId: '1:727531645851:web:f2998046d7a9445e334f3e',
    messagingSenderId: '727531645851',
    projectId: 'instagram-clone-2b309',
    authDomain: 'instagram-clone-2b309.firebaseapp.com',
    storageBucket: 'instagram-clone-2b309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4LDxtJaymBDmr1D8ZwKFhckErlWerBW8',
    appId: '1:727531645851:android:0138a0b64e6d5fad334f3e',
    messagingSenderId: '727531645851',
    projectId: 'instagram-clone-2b309',
    storageBucket: 'instagram-clone-2b309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOjTKgCe7m2ysEoC1hNnZVxxEiLWOtDlY',
    appId: '1:727531645851:ios:51a9ab38cc8e8799334f3e',
    messagingSenderId: '727531645851',
    projectId: 'instagram-clone-2b309',
    storageBucket: 'instagram-clone-2b309.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOjTKgCe7m2ysEoC1hNnZVxxEiLWOtDlY',
    appId: '1:727531645851:ios:14fcdabaa9faeb5e334f3e',
    messagingSenderId: '727531645851',
    projectId: 'instagram-clone-2b309',
    storageBucket: 'instagram-clone-2b309.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
